version: '3'
services:
  api:
    image: node:alpine
    volumes:
      - type: bind
        source: ./api
        target: /code
    working_dir: /code
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASS}
    volumes:
      - ${SEED_FILE_PATH}:/docker-entrypoint-initdb.d/:ro
