version: '3'
services:
  api:
    container_name: test_api
    environment:
      DB_CONNECTION_URI: mongodb://${DATABASE_USER}:${DATABASE_PASS}@db:27017
      DB_NAME: telechart_test
      PORT: 5000
    depends_on:
      - db
    tty: true
  db:
    container_name: test_db
    environment:
      MONGO_INITDB_DATABASE: telechart_test
    volumes:
      - test_data:/var/lib/mongodb/data
volumes:
  test_data:
networks:
  default:
    name: test
